language: node_js
install: npm install
env:
  - dbConnection=mongodb+srv://cyimana:Cyfaisal1998@portfolio.pgjtx.mongodb.net/portfoliodb?retryWrites=true&w=majority
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: true
script:
  - npm test
