language: node_js
install: npm install
env:
  - dbConnection=mongodb+srv://cyimana:Cyfaisal1998@portfolio.pgjtx.mongodb.net/portfoliodb?retryWrites=true&w=majority
  - KEY=cyimana:Cyfaisal1998
  - CLOUDINARY_URL=cloudinary://569557385459476:csMHSwIagQZxdpudezg-nuUG3cY@cyimana
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: true
script:
  - npm test
after_success:
  - npm run coverage
